name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ 'rc-*' , 'master' ]

jobs:

  test:
    name: Build + Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make pkg-config libssl-dev

      - name: Configure + Build (with tests)
        run: |
          make test examples
