name: Formatting Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ 'rc-*' , 'master' ]

jobs:
  check:
    name: Lint (clang-format)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          apt-get update -y && apt-get install python3-pip -y
          pip install clang-format==20.1.8
          echo "clang-format version: $(clang-format --version)"

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          make check

